# cpu型密集异步任务中同种类任务最大运行数
cpu_asyncio_task: 5

# io型密集异步任务中同种类任务最大运行数
io_asyncio_task: 5

# cpu型密集线性任务中同种类任务最大运行数
cpu_liner_task: 5

# io型密集线性任务中同种类任务最大运行数
io_liner_task: 5

# When there are no tasks for many seconds, close the task scheduler(seconds)
max_idle_time: 6

# When a task runs for a long time without finishing, it is forced to end(seconds)
watch_dog_time: 60

# The maximum number of records that can be stored in a task status
maximum_task_info_storage: 20

# How many seconds to check whether the task status is correct,recommended a longer interval(seconds)
status_check_interval: 800