# The maximum number of linear tasks that can run at the same time
line_task_max: 10

# The maximum number of queues for a asyncio task
maximum_queue_async: 30

# The maximum number of queues for a linear task
maximum_queue_line: 30

# When there are no tasks for many seconds, close the task scheduler(seconds)
max_idle_time: 6

# When a task runs for a long time without finishing, it is forced to end(seconds)
watch_dog_time: 6

# The maximum number of records that can be stored in a task status
maximum_task_info_storage: 20

# The maximum number of tasks that run in a single event loop
maximum_event_loop_tasks: 3